apiVersion: v1
kind: Pod
metadata:
  name: pod2
  labels:
    app: two-containers
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - name: nginx-port
      containerPort: 80
  - name: watcher
    image: afakharany/watcher
