apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
specs:
  ports:
  - port: 31001
    targetPort: nodejs-port
    protocol: TCP
  selector:
    app: helloworld
  type: NodePort
 
    
    
